// Reads dimensions of every WebP under public/images/ and writes a TS map to
// src/generated/imageSizes.ts so <Img> can render width/height attributes
// and the browser reserves layout space before the image loads.
//
// Run: node scripts/generateImageSizes.mjs

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, posix, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const imagesDir = join(root, "public", "images");
const outFile = join(root, "src", "generated", "imageSizes.ts");
const urlPrefix = "/github-portfolio/images/";

async function walk(dir) {
    const out = [];
    const entries = await readdir(dir, { withFileTypes: true });
    for (const e of entries) {
        const p = join(dir, e.name);
        if (e.isDirectory()) out.push(...(await walk(p)));
        else if (e.isFile() && p.toLowerCase().endsWith(".webp")) out.push(p);
    }
    return out;
}

function readWebpSize(buf) {
    if (buf.length < 30) throw new Error("file too small for WebP header");
    if (buf.toString("ascii", 0, 4) !== "RIFF" || buf.toString("ascii", 8, 12) !== "WEBP") {
        throw new Error("not a WebP file");
    }
    const chunk = buf.toString("ascii", 12, 16);

    if (chunk === "VP8 ") {
        // Lossy: start code 0x9D 0x01 0x2A at offset 23, then width/height (14-bit LE)
        if (buf[23] !== 0x9d || buf[24] !== 0x01 || buf[25] !== 0x2a) {
            throw new Error("VP8 start code not found");
        }
        const w = buf.readUInt16LE(26) & 0x3fff;
        const h = buf.readUInt16LE(28) & 0x3fff;
        return { width: w, height: h };
    }

    if (chunk === "VP8L") {
        // Lossless: signature 0x2F at offset 20, then 4 packed bytes
        if (buf[20] !== 0x2f) throw new Error("VP8L signature not found");
        const b0 = buf[21], b1 = buf[22], b2 = buf[23], b3 = buf[24];
        const width = 1 + (((b1 & 0x3f) << 8) | b0);
        const height = 1 + (((b3 & 0x0f) << 10) | (b2 << 2) | ((b1 & 0xc0) >> 6));
        return { width, height };
    }

    if (chunk === "VP8X") {
        // Extended: canvas dims at offset 24..29 (3 bytes LE each, value is dim - 1)
        const w = 1 + (buf[24] | (buf[25] << 8) | (buf[26] << 16));
        const h = 1 + (buf[27] | (buf[28] << 8) | (buf[29] << 16));
        return { width: w, height: h };
    }

    throw new Error(`unknown WebP chunk: ${chunk}`);
}

async function main() {
    const files = await walk(imagesDir);
    files.sort();

    const entries = [];
    for (const file of files) {
        const buf = await readFile(file);
        const { width, height } = readWebpSize(buf);
        const rel = relative(imagesDir, file).split(sep).join(posix.sep);
        const url = urlPrefix + rel;
        entries.push({ url, width, height });
    }

    const lines = [
        "// AUTO-GENERATED by scripts/generateImageSizes.mjs. Do not edit by hand.",
        "export const imageSizes: Record<string, { width: number; height: number }> = {",
        ...entries.map((e) => `    ${JSON.stringify(e.url)}: { width: ${e.width}, height: ${e.height} },`),
        "};",
        "",
    ];

    await mkdir(dirname(outFile), { recursive: true });
    await writeFile(outFile, lines.join("\n"), "utf8");
    console.log(`Wrote ${entries.length} entries to ${relative(root, outFile)}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
